-- You can add your own plugins here or in other files in this directory!
--  I promise not to create any merge conflicts in this directory :)
--
-- See the kickstart.nvim README for more information
return {
  'AndrewRadev/splitjoin.vim',
  'FabijanZulj/blame.nvim',
  'HerringtonDarkholme/yats.vim',
  'JMarkin/cmp-diag-codes',
  'RRethy/nvim-treesitter-endwise',
  'ahmedkhalf/project.nvim',
  'akinsho/git-conflict.nvim',
  'cespare/vim-toml',
  'cuducos/yaml.nvim',
  'direnv/direnv.vim',
  'echasnovski/mini.nvim',
  'elixir-editors/vim-elixir',
  'evanleck/vim-svelte',
  'fladson/vim-kitty',
  'honza/vim-snippets',
  'hrsh7th/cmp-cmdline',
  'hrsh7th/cmp-nvim-lsp',
  'hrsh7th/cmp-path',
  'iamcco/markdown-preview.nvim',
  'junegunn/fzf.vim',
  'lowitea/aw-watcher.nvim',
  'm00qek/baleia.nvim',
  'mechatroner/rainbow_csv',
  'mg979/vim-visual-multi',
  'monaqa/dial.nvim',
  'norcalli/nvim-colorizer.lua',
  'nvim-focus/focus.nvim',
  'nvim-lualine/lualine.nvim',
  'nvim-neotest/neotest',
  'nvim-telekasten/telekasten.nvim',
  'olimorris/neotest-rspec',
  'pangloss/vim-javascript',
  'saadparwaiz1/cmp_luasnip',
  'samjwill/nvim-unception',
  'tommcdo/vim-exchange',
  'topaxi/gh-actions.nvim',
  'tpope/vim-abolish',
  'tpope/vim-bundler',
  'tpope/vim-bundler',
  'tpope/vim-dadbod',
  'tpope/vim-dispatch',
  'tpope/vim-eunuch',
  'tpope/vim-fugitive',
  'tpope/vim-obsession',
  'tpope/vim-projectionist',
  'tpope/vim-rails',
  'tpope/vim-rake',
  'tpope/vim-sleuth', -- Detect tabstop and shiftwidth automatically
  'tpope/vim-unimpaired',
  'vim-crystal/vim-crystal',
  'vim-ruby/vim-ruby',
  'vim-test/vim-test',
  'williamboman/mason-lspconfig.nvim',

}
